language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
    
before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ 5.[56] ]] ; then echo yes | pecl install apcu-4.0.10; fi;
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-add ./tests/apc.ini; fi;
  - composer install --dev --prefer-source
  
script:
  - mkdir -p build/logs
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls -v
  - CODECLIMATE_REPO_TOKEN=349c0ea39e9bb39c0c259db553ef9a21e974bb40660c59a16cb77630f3cdfdf9 ./vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
