language: php

php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - chmod +x ./tests/install-apcu.sh
  - ./tests/install-apcu.sh
  - phpenv config-add tests/$TRAVIS_PHP_VERSION.ini
  - phpenv config-add tests/apc.ini
  - composer install --dev --prefer-source

script: phpunit
