language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    
before_script:
  - chmod +x ./tests/install-apcu.sh
  - ./tests/install-apcu.sh
  - phpenv config-add tests/php.ini
  - phpenv config-add tests/apc.ini
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - phpunit

after_script:
  - php vendor/bin/coveralls -v
