
<div class="prismic-toolbar">
    <form class="inner" action="<?php echo $this->url('prismic-ref'); ?>" method="get">
        <p>Content Preview:
        <?php
        $this->selectRef->setAttribute('class', '');
        echo $this->formSelect($this->selectRef);
        ?>
        <input type="hidden" name="url" value="<?php echo $this->escapeHtmlAttr($this->url); ?>">
        <button type="submit" name="change-ref" value="1">Change</button></p>
    </form>

</div>
